
INSERT INTO USERS(EMAIL, NAME, PASSWORD, USERNAME) VALUES('owner@email.com','owner','$2a$10$gHSI1RfHJcyIxl1JX8BalezMm7UNIeX.6yqfrZRomU50sFHz8dnzG','owner');
INSERT INTO USERS(EMAIL, NAME, PASSWORD, USERNAME) VALUES('admin@email.com','admin','$2a$10$gHSI1RfHJcyIxl1JX8BalezMm7UNIeX.6yqfrZRomU50sFHz8dnzG','admin');
INSERT INTO USERS(EMAIL, NAME, PASSWORD, USERNAME) VALUES('user@email.com','user','$2a$10$gHSI1RfHJcyIxl1JX8BalezMm7UNIeX.6yqfrZRomU50sFHz8dnzG','user');
INSERT INTO USERS(EMAIL, NAME, PASSWORD, USERNAME) VALUES('customer@email.com','customer','$2a$10$gHSI1RfHJcyIxl1JX8BalezMm7UNIeX.6yqfrZRomU50sFHz8dnzG','customer');

INSERT INTO ROLES(NAME) VALUES('ROLE_CUSTOMER');
INSERT INTO ROLES(NAME) VALUES('ROLE_USER');
INSERT INTO ROLES(NAME) VALUES('ROLE_ADMIN');
INSERT INTO ROLES(NAME) VALUES('ROLE_OWNER');

INSERT INTO USER_ROLES (USER_ID,ROLE_ID) VALUES(SELECT id FROM USERS WHERE NAME='owner',SELECT id FROM ROLES WHERE NAME='ROLE_OWNER');
INSERT INTO USER_ROLES (USER_ID,ROLE_ID) VALUES(SELECT id FROM USERS WHERE NAME='admin',SELECT id FROM ROLES WHERE NAME='ROLE_ADMIN');
INSERT INTO USER_ROLES (USER_ID,ROLE_ID) VALUES(SELECT id FROM USERS WHERE NAME='user',SELECT id FROM ROLES WHERE NAME='ROLE_USER');
INSERT INTO USER_ROLES (USER_ID,ROLE_ID) VALUES(SELECT id FROM USERS WHERE NAME='customer',SELECT id FROM ROLES WHERE NAME='ROLE_CUSTOMER');